
import { Assistant } from "next/font/google";
import "./globals.css";

const assistant = Assistant({ subsets: ["latin"] });

export const metadata = {
  title: "senior year 360",
  description: "Generated by senior year 360",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="google-site-verification" content="mubN99e8y7r0qbeHHmSSFT3lsiYzXMtIGhYc0nEI32E" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Patua+One&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />

        <link rel="stylesheet" type="text/css" charSet="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"/>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"/>

      </head>

      <body className={assistant.className}>{children}</body>
      
    </html>
  );
}
